/**
 * Tests for src/api/library.ts — the native /library + /stats port.
 *
 * No network and no fixtures: the Tauri `invoke` bridge and the @/state/db
 * allPaths store are mocked. Expected titles/subs/years were generated by
 * running the sidecar's own Python functions (scan_library item building,
 * _movie_title) on the same filenames, so the port is checked against the
 * Python ground truth byte-for-byte.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"

const { invokeMock, allPathsMock } = vi.hoisted(() => ({
  invokeMock: vi.fn(),
  allPathsMock: vi.fn(),
}))

vi.mock("@tauri-apps/api/core", () => ({ invoke: invokeMock }))
vi.mock("@/state/db", () => ({ allPaths: allPathsMock }))

import {
  buildItems,
  library,
  movieTitle,
  parseMovieEntry,
  stats,
  tvTitle,
} from "@/api/library"

interface ScanFile {
  name: string
  path: string
  size: number
}

function scanFile(name: string, folder: string, size = 0): ScanFile {
  return { name, path: `${folder}/${name}`, size }
}

/** Route invoke("scan_videos"/"disk_stats") to per-folder canned results. */
function routeInvoke(opts: {
  scans?: Record<string, ScanFile[] | Error>
  disks?: Record<string, { free: number; total: number } | Error>
}) {
  invokeMock.mockImplementation(async (cmd: string, args: { path: string }) => {
    const table = cmd === "scan_videos" ? opts.scans : opts.disks
    const hit = table?.[args.path]
    if (hit === undefined) throw new Error(`not a directory: ${args.path}`)
    if (hit instanceof Error) throw hit
    return hit
  })
}

beforeEach(() => {
  invokeMock.mockReset()
  allPathsMock.mockReset()
  // Pretend we are inside the Tauri shell (node has no `window`).
  vi.stubGlobal("window", { __TAURI_INTERNALS__: {} })
})

afterEach(() => {
  vi.unstubAllGlobals()
})

// ------------------------------------------------------------------ ad / vrc

describe("library() — ad/vrc items", () => {
  it("parses codes, VR flags and subs like the sidecar", async () => {
    allPathsMock.mockResolvedValue({ ad: "/lib/ad", vrc: "/lib/vrc" })
    routeInvoke({
      scans: {
        "/lib/ad": [
          scanFile("SSIS-001.mp4", "/lib/ad", 4_900_000_000),
          scanFile("SIVR-100 [VR].mp4", "/lib/ad", 1024),
          scanFile("random-clip.mp4", "/lib/ad", 0),
        ],
        "/lib/vrc": [scanFile("ABCD-123.mp4", "/lib/vrc", 512)],
      },
    })

    const res = await library()
    expect(res.ok).toBe(true)
    expect(res.count).toBe(4)
    expect(res.counts).toEqual({ ad: 3, vrc: 1 })

    const [plain, vrLabeled, noCode, vrcItem] = res.items
    // plain code in the ad folder
    expect(plain).toMatchObject({
      fname: "SSIS-001.mp4",
      path: "/lib/ad/SSIS-001.mp4",
      cat: "ad",
      size: "4.6 GB", // humanSize ground truth: Python human_size(4900000000)
      state: "own",
      cover: "",
      ar: 0.72,
      code: "SSIS-001",
      title: "SSIS-001",
      vr: false,
      sub: "SSIS-001",
    })
    // VR label + [VR] marker forces vr=true even in the flat "ad" category
    expect(vrLabeled).toMatchObject({
      code: "SIVR-100",
      vr: true,
      sub: "VR · SIVR-100",
    })
    // no parsable code: title falls back to the basename (42-char cut), sub ""
    expect(noCode).toMatchObject({
      code: "",
      title: "random-clip",
      vr: false,
      sub: "",
    })
    // everything in vrc is VR by definition
    expect(vrcItem).toMatchObject({
      cat: "vrc",
      code: "ABCD-123",
      vr: true,
      sub: "VR · ABCD-123",
    })
  })

  it("cuts long code-less basenames to 42 chars", async () => {
    allPathsMock.mockResolvedValue({ ad: "/lib/ad" })
    const long = "a very long descriptive clip name with no code at all.mp4"
    routeInvoke({ scans: { "/lib/ad": [scanFile(long, "/lib/ad")] } })
    const res = await library()
    expect(res.items[0].title).toBe(long.slice(0, -4).slice(0, 42))
    expect(res.items[0].title.length).toBe(42)
  })
})

// ------------------------------------------------------------------ tv

describe("library() — tv items", () => {
  it("cleans gnarly real-style names like the Python regex chain", async () => {
    allPathsMock.mockResolvedValue({ tv: "/lib/tv" })
    routeInvoke({
      scans: {
        "/lib/tv": [
          scanFile("Breaking.Bad.S01E03.1080p.WEB-DL.x264.mkv", "/lib/tv"),
          scanFile(
            "[SubsPlease] Sousou no Frieren - 28 (1080p) [ABCD1234].mkv",
            "/lib/tv"
          ),
          scanFile("ダンジョン飯 第3話 「動く鎧」.mp4", "/lib/tv"),
          scanFile("Andor.S02E05.2160p.WEB.h265-ETHEL.mkv", "/lib/tv"),
        ],
      },
    })

    const res = await library()
    // Ground truth from running the sidecar's tv branch on the same names.
    expect(
      res.items.map((it) => ({ title: it.title, sub: it.sub, ar: it.ar }))
    ).toEqual([
      { title: "Breaking Bad", sub: "S01E03", ar: 0.7 },
      // faithful quirk: the dangling "(" survives the sidecar's strip set too
      { title: "SubsPlease] Sousou no Frieren - 28 (", sub: "", ar: 0.7 },
      { title: "ダンジョン飯", sub: "", ar: 0.7 }, // 第3話 marker cut
      { title: "Andor", sub: "S02E05", ar: 0.7 },
    ])
    expect(res.counts).toEqual({ tv: 4 })
  })

  it("tvTitle drops trailing bare episode numbers (with END/FIN)", () => {
    expect(tvTitle("Frieren 28")).toEqual({ title: "Frieren", sub: "" })
    expect(tvTitle("Frieren 28 END")).toEqual({ title: "Frieren", sub: "" })
  })
})

// ------------------------------------------------------------------ mov

describe("library() — mov items", () => {
  it("extracts title + year via the _movie_title port", async () => {
    allPathsMock.mockResolvedValue({ mov: "/lib/mov" })
    routeInvoke({
      scans: {
        "/lib/mov": [
          scanFile("Heat.1995.1080p.BluRay.x265.mkv", "/lib/mov"),
          scanFile("The.Matrix.1999.REMUX.mkv", "/lib/mov"),
          scanFile("Some Movie.mp4", "/lib/mov"),
        ],
      },
    })

    const res = await library()
    expect(
      res.items.map((it) => ({
        title: it.title,
        year: it.year,
        sub: it.sub,
        ar: it.ar,
      }))
    ).toEqual([
      { title: "Heat", year: "1995", sub: "1995", ar: 0.675 },
      { title: "The Matrix", year: "1999", sub: "1999", ar: 0.675 },
      { title: "Some Movie", year: "", sub: "", ar: 0.675 },
    ])
  })

  it("movieTitle keeps the sidecar's first-year quirk", () => {
    // Python ground truth: the FIRST year token wins (2049), the second stays.
    expect(movieTitle("Blade.Runner.2049.2017.1080p.BluRay.x264.mkv")).toEqual({
      title: "Blade Runner 2017",
      year: "2049",
    })
  })
})

// ------------------------------------------------------------ structure-aware buildItems

describe("buildItems — structure-aware grouping", () => {
  it("parses a movie folder by its clean YEAR.Title name (not the inner file)", () => {
    const root = "/lib/mov"
    const items = buildItems("mov", root, [
      scanFile("[DBD-Raws][Perfect Blue][1080P][x265].mkv", `${root}/1997.パーフェクトブルー`, 9e9),
      scanFile("._junk.mkv", `${root}/1997.パーフェクトブルー`, 10),
    ])
    expect(items).toHaveLength(1)
    expect(items[0]).toMatchObject({ title: "パーフェクトブルー", year: "1997", cat: "mov" })
  })

  it("collapses a series folder's episodes into one show item", () => {
    const root = "/lib/tv"
    const show = `${root}/カウボーイビバップ`
    const items = buildItems("tv", root, [
      scanFile("Cowboy Bebop 01 [BD].mkv", show, 1e9),
      scanFile("Cowboy Bebop 02 [BD].mkv", show, 1e9),
      scanFile("Cowboy Bebop 03 [BD].mkv", show, 1e9),
    ])
    expect(items).toHaveLength(1)
    expect(items[0]).toMatchObject({ title: "カウボーイビバップ", sub: "3 episodes" })
  })

  it("merges multi-part JAV files (-A/-B/-C) into one item by code", () => {
    const root = "/lib/ad"
    const items = buildItems("ad", root, [
      scanFile("ABP-601-A.mp4", root, 2e9),
      scanFile("ABP-601-B.mp4", root, 2e9),
      scanFile("ABF-032.mp4", root, 3e9),
    ])
    expect(items.map((i) => i.code).sort()).toEqual(["ABF-032", "ABP-601"])
    expect(items).toHaveLength(2)
  })

  it("composes NFD names to NFC so Japanese titles match upstream", () => {
    // NFD: "ゴ" decomposed as コ + U+3099 — must come back composed.
    const nfd = "2003.東京ゴッドファーザーズ".normalize("NFD")
    const root = "/lib/mov"
    const items = buildItems("mov", root, [scanFile(`${nfd}.mkv`, root, 1e9)])
    expect(items[0].title).toBe("東京ゴッドファーザーズ".normalize("NFC"))
    expect(items[0].title.normalize("NFD")).not.toBe(items[0].title) // proves it's NFC
  })
})

describe("parseMovieEntry", () => {
  it("trusts a leading year (file or folder), handles CJK and number-titles", () => {
    expect(parseMovieEntry("1990.GoodFellas.mkv")).toEqual({ title: "GoodFellas", year: "1990" })
    expect(parseMovieEntry("2004.2046.mkv")).toEqual({ title: "2046", year: "2004" })
    expect(parseMovieEntry("1997.パーフェクトブルー")).toEqual({ title: "パーフェクトブルー", year: "1997" })
  })
  it("falls back to movieTitle when the year is not leading", () => {
    expect(parseMovieEntry("Heat.1995.1080p.BluRay.mkv")).toEqual({ title: "Heat", year: "1995" })
  })
})

// ------------------------------------------------------------------ aggregation

describe("library() — aggregation", () => {
  it("walks cats in mov,tv,ad,vrc order, skips unset and failing folders", async () => {
    allPathsMock.mockResolvedValue({
      mov: "/lib/mov",
      tv: "/lib/tv", // scan rejects (missing folder) -> cat skipped
      ad: "/lib/ad",
      // vrc unset -> never invoked
    })
    routeInvoke({
      scans: {
        "/lib/mov": [scanFile("Heat.1995.mkv", "/lib/mov")],
        "/lib/tv": new Error("not a directory: /lib/tv"),
        "/lib/ad": [
          scanFile("SSIS-001.mp4", "/lib/ad"),
          scanFile("SSIS-002.mp4", "/lib/ad"),
        ],
      },
    })

    const res = await library()
    expect(res.items.map((it) => it.cat)).toEqual(["mov", "ad", "ad"])
    expect(res.count).toBe(3)
    expect(res.counts).toEqual({ mov: 1, ad: 2 })
    expect(invokeMock).not.toHaveBeenCalledWith(
      "scan_videos",
      expect.objectContaining({ path: expect.stringContaining("vrc") })
    )
  })
})

// ------------------------------------------------------------------ stats

describe("stats()", () => {
  it("reports per-cat disk stats, offline zeros for failures and unset cats", async () => {
    allPathsMock.mockResolvedValue({ mov: "/lib/mov", tv: "/lib/tv" })
    routeInvoke({
      scans: {
        "/lib/mov": [
          scanFile("a.mkv", "/lib/mov"),
          scanFile("b.mkv", "/lib/mov"),
        ],
        "/lib/tv": new Error("boom"),
      },
      disks: {
        "/lib/mov": { free: 111, total: 999 },
        "/lib/tv": new Error("volume gone"),
      },
    })

    const res = await stats()
    expect(res.ok).toBe(true)
    expect(res.disks.mov).toEqual({
      path: "/lib/mov",
      online: true,
      free: 111,
      total: 999,
      files: 2,
    })
    // both invokes failed -> offline zeros, but the call still resolves
    expect(res.disks.tv).toEqual({
      path: "/lib/tv",
      online: false,
      free: 0,
      total: 0,
      files: 0,
    })
    // unset cats are present with empty path + zeros (Python loops all four)
    expect(res.disks.ad).toEqual({
      path: "",
      online: false,
      free: 0,
      total: 0,
      files: 0,
    })
    expect(res.disks.vrc.online).toBe(false)
  })

  it("keeps online=true with files=0 when only the scan fails", async () => {
    allPathsMock.mockResolvedValue({ ad: "/lib/ad" })
    routeInvoke({
      scans: { "/lib/ad": new Error("walk failed") },
      disks: { "/lib/ad": { free: 5, total: 10 } },
    })
    const res = await stats()
    expect(res.disks.ad).toEqual({
      path: "/lib/ad",
      online: true,
      free: 5,
      total: 10,
      files: 0,
    })
  })
})

// ------------------------------------------------------------------ non-Tauri host

describe("outside Tauri", () => {
  it("returns empty-but-valid shapes without touching the db or invoke", async () => {
    vi.unstubAllGlobals() // node: no window at all -> not Tauri

    const lib = await library()
    expect(lib).toEqual({ ok: true, items: [], count: 0, counts: {} })

    const st = await stats()
    expect(st.ok).toBe(true)
    for (const cat of ["mov", "tv", "ad", "vrc"] as const) {
      expect(st.disks[cat]).toEqual({
        path: "",
        online: false,
        free: 0,
        total: 0,
        files: 0,
      })
    }

    expect(allPathsMock).not.toHaveBeenCalled()
    expect(invokeMock).not.toHaveBeenCalled()
  })
})
